### ISSUE TITLE
INTERLEAVE SCHEDULING BETWEEN GEARMAN QUEUE 

### ISSUE THREAD

**Issue by sdouce** [sni/mod_gearman#140]
Hello Sven ,
This is not really an Issue but more  a question/evolution request about scheduling with gearman queue.. 

In my example i split  my check with gearman hostgroup queue, to obtain that my SAP are executed from dedicated worker . 
But Scheduling is global from back-end , and i don't find the way to sleek my polling between queue... 

Do you have any clue about this ? 
Sorry for my english ;-)

**Comment by sdouce** [comment]
Not really an issue , but more a code request ... The only way i found to do it is to add backend (scheduling split) ... 
Is there any possibility to do that through gearman ?

**Comment by sni** [comment]
i still have no idea what you really want. Gearman is used for the transport and the worker simply runs the checks.
Now if you need to run some checks sequentially, you can do that by limiting the max-workers for that queue.
If you want to leverage the amount of checks done at a time, you can do that with the `core scheduling` addon in Thruk: https://thruk.org/documentation/plugins.html#core-scheduling-graph

**Comment by ranjithkodumbu** [comment]
Hi Sni, I think sdouce trying to ask "is it possible to take out the scheduler in a central place". For.g. In case of Nagios, currently check scheduler is controlled by Nagios server and gearman broker module intercepts the checks and add the check requests in the respective gearman queue. Instead of that is it possible to controller the scheduler in gearman server itself. I think that is waht sdouce is trying to ask.

**Comment by sni** [comment]
i see. Well, gearman/mod-gearman requires some external scheduler but it doesn't have to be nagios. It could be an kind of gearman client which submits jobs and reads the results.
