### ISSUE TITLE
drop nagios 3, nagios 4 and icinga 1 support? what does this mean for Nagios and mod_gearman?

### ISSUE THREAD

**Issue by molekuul** [sni/mod_gearman#158]
I don't know if this is the right place to put this question, but I couldn't find another place to ask this.
I see in the commits, and change file: 
"drop nagios 3, nagios 4 and icinga 1 support" 

What does this mean for the use of mod_gearman for NagiosXI 5.x.x? NagiosXI 5.8.1 still uses Nagios Core 4.4.6 
Does this mean new versions of mod_gearman can't be used with Nagios anymore? 
Does this mean the development of fixes and features  for the use of mod_gearman in a Nagios environment is stopped?

Kind regards,
Joris Weijters

**Comment by sni** [comment]
Basically this just states how it is already, i have no business in nagios and no access to any xi, so the nagios part was unmaintained for years anyway but makes development for naemon more difficult because tons of `#ifdef`s.
But tbh, there is not much going on in the module anyway. It has been stable for serveral years now and the only thing changed
was the worker part which has been rewritten in go, see https://github.com/ConSol/mod-gearman-worker-go along with the
tools send_gearman and stuff. So if there would be any development, it will be there.
And if there really would be bugfixes, we could still branch out the 3.x branch and do bugfixes from there.
